twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        relative_uploads_directory: '%relative_uploads_directory%'
when@test:
    twig:
        strict_variables: true
